### ISSUE TITLE
Validate RSI Calculation

### ISSUE THREAD

**Issue by drdDavi** [Bitvested/ta.js#12]
When running the RSI the resulting output doesnt align with any other library.

`   close = [
      172.789993, 172.550003, 168.880005, 167.300003, 164.320007, 160.070007, 162.740005, 164.850006, 165.119995, 163.199997, 166.56, 166.23,
      163.17, 159.3, 157.44, 162.95, 158.52, 154.73, 150.62, 155.09, 159.59, 160.62, 163.98, 165.38, 168.82, 170.21, 174.07, 174.72, 175.6,
      178.96, 177.77, 174.61, 174.31, 178.44, 175.06, 171.83, 172.14, 170.09, 165.75, 167.66, 170.4, 165.29, 165.07, 167.4, 167.23, 166.42,
      161.79, 162.88, 156.8, 156.57
    ];`

   ` const rsi14 = await ta.rsi(close, 14);`

`
result   [
      27.74661147031628, 26.33885045671019, 41.220006984308256, 38.01200628563883, 37.18940713554575, 37.32902951513339, 40.214880069939134,
      43.659586224586825, 44.673301499211625, 50.892860515600226, 48.58581016299136, 52.88869060896722, 58.155699721964815, 67.11471610660485,
      70.60085836909873, 66.9525596354865, 78.20088300220749, 84.24494649227115, 86.69317834200062, 83.69565217391303, 83.48134991119004,
      73.67213114754098, 62.9239380968061, 61.54371584699453, 52.27680172104699, 42.769130998702956, 38.9061959155417, 43.02775984506133,
      35.35927293382561, 28.344246959775447, 34.38723276121648, 37.7895433487756, 37.162382037097274, 23.34293948126799, 28.956461644782294,
      26.360490720352303, 25.449385052034103
    ];
`

the same result from using python

`df['rsi(14)'] = ta.momentum.rsi(df['close'], 14)`

```
result from python 
[53.11352    52.70502392 46.78009175 44.46268251 40.39784045 35.42388839
 40.38950504 44.05092927 44.52052663 41.83171379 47.77591931 47.26505326
 42.70500973 37.74520229 35.60486603 45.46954028 40.14482839 36.23527393
 32.53498553 39.7422035  45.99678593 47.34401732 51.58700049 53.27640362
 57.22611274 58.74372189 62.70132145 63.33907943 64.23079379 67.48297331
 65.22121366 59.51673278 58.98923713 63.75217812 57.83246836 52.78804561
 53.20987594 50.02667325 44.02232863 47.03519379 51.1011733  44.27480827
 44.00227457 47.67580796 47.43132054 46.21523428 39.91551047 41.9226311
 34.91615995 34.68003641]

```

the python result alights with trading view and other apps

is there something different here with the calculations or am I doing something wrong?

**Comment by Vultwo** [comment]
The tradingview version of the RSI is actually the WRSI indicator.
You should be fine when you use `ta.wrsi`
My results match up with tradingview.
Let me know if it's still not working.

**Comment by drdDavi** [comment]
I can confirm its working as expected...strange that everyone else calls it rsi...

Any chance to make a dart/flutter library :)

Thanks again for the good work.

**Comment by Vultwo** [comment]
Yes, I will keep a dart/flutter library in mind.
Don't expect it any time soon, however.
