### ISSUE TITLE
Lagging Indicators not using a moving window calculation

### ISSUE THREAD

**Issue by HudsonRapidDevelopment** [Bitvested/ta.js#13]
I am having issues with lagging indicators, the values are not in tandem with the current price timestamp. The trading view charting platform when calculating MACD will calculate a value for the current time through a rolling window like shown in the images below. How do I achieve this with the MACD function provided? 

![image](https://user-images.githubusercontent.com/67387499/166492981-38a445ab-2605-41f3-8c32-6666aa3a602e.png)
![image](https://user-images.githubusercontent.com/67387499/166493110-9e9b5176-e12d-4e5d-a0a2-b543c70ee755.png)

**Comment by Vultwo** [comment]
Hi,

Did you forget to splice the price data?
I think your lengths are not aligning.
To fix this you should check of which indicator the length is the lowest.
Then do:
`
array.splice(0, array.length-lowest)
`
So all arrays are of the same length.

**Comment by HudsonRapidDevelopment** [comment]
> 

Thank you for the quick reply, and it is true. There is an array of some arbitrary length N that I have created which is comprised of [TIMESTAMP, CLOSE DATA, VOLUME] then I am passing it to the function as 

```
                        for (i=0; i < JSON_TIMESTAMP_DATA.length; i++) {
                            let dateOBJ = new Date(JSON_TIMESTAMP_DATA[i] * 1000);
                            let isoString = dateOBJ.toISOString();
                            isoString = isoString.slice(0,19);
                            JSON_TIMESTAMP_DATA[i] = isoString;
                            JSON_TS_VOL_DATA.push([JSON_CLOSE_DATA[i], JSON_VOL_DATA[i]]);
                            JSON_CLH_DATA.push([JSON_HIGH_DATA[i], JSON_CLOSE_DATA[i], JSON_LOW_DATA[i]]);
                        }
                        let joinedData = [JSON_TIMESTAMP_DATA, JSON_CLOSE_DATA, JSON_VOL_DATA];
                        let RSIPrice    = rsi(joinedData[1], 12);
                        let MACD        = macd(joinedData[1], 12, 26, 3);
                        let SO          = stoch(JSON_CLH_DATA, 12, 3, 3);
```

Perhaps its something that is being done with the plotting library I am using

**Comment by Vultwo** [comment]
What if you try:
`
                        for (i=0; i < JSON_TIMESTAMP_DATA.length; i++) {
                            let dateOBJ = new Date(JSON_TIMESTAMP_DATA[i] * 1000);
                            let isoString = dateOBJ.toISOString();
                            isoString = isoString.slice(0,19);
                            JSON_TIMESTAMP_DATA[i] = isoString;
                            JSON_TS_VOL_DATA.push([JSON_CLOSE_DATA[i], JSON_VOL_DATA[i]]);
                            JSON_CLH_DATA.push([JSON_HIGH_DATA[i], JSON_CLOSE_DATA[i], JSON_LOW_DATA[i]]);
                        }
                        let joinedData = [JSON_TIMESTAMP_DATA, JSON_CLOSE_DATA, JSON_VOL_DATA];
                        let RSIPrice    = await rsi(joinedData[1], 12);
                        let MACD        = await macd(joinedData[1], 12, 26, 3);
                        let SO          = await stoch(JSON_CLH_DATA, 12, 3, 3);

                        joinedData[1].splice(0,joinedData[1].length-MACD.length)
                        RSIPrice.splice(0,RSIPrice.length-MACD.length);
                        SO.splice(0,SO.length-MACD.length);
`
In case MACD contains the lowest amount of elements.

**Comment by HudsonRapidDevelopment** [comment]
I implemented the changes you provided and to no avail, I believe I poorly worded my original question. 

On TradingView I can add indicators like MACD and RSI, these indicators will take an array price points and calculate the relevant values. The resultant looks something like PICTURE (1). Where there is a value present at the current time step of 16:45 for both MACD and RSI, even though these are lagging indicators.

When trying to calculate MACD and RSI from an array of price points I am returned not an equal sized array but an array of the size based on the ARRAY.SPLICE() method so what I am left with is an indicator when plotted it is trailing behind by N (Time period for calculation to be made) away from the current price. 

I want MACD and RSI to be aligned with the current time steps price, and this would be achieved through a continuous average calculation if I recall correctly. In PYTHON there is pandas which you can use EWM which has this functionality

**Comment by Vultwo** [comment]
Sorry, I am afraid I still don't fully get what you are trying to get at 😂.
Using this library I have always been able to match the indicators at the current timestep.
I think your issue is originating from somewhere else.
Let me know if you have fixed it.

**Comment by HudsonRapidDevelopment** [comment]
> Sorry, I am afraid I still don't fully get what you are trying to get at 😂. Using this library I have always been able to match the indicators at the current timestep. I think your issue is originating from somewhere else. Let me know if you have fixed it.

I just realized what was going on, its not an issue with the library. I apologize, you don't fill the values with NAN or 0 before the calculation is made so the array is not of equal length (obviously) so when I am plotting it, it is assuming a direct 1-1 relationship with the X-axis of timedate values which is incorrect. The values should be pushed by some amount so that the final datapoint of the MACD RSI and STOCH match up with the price points as they should.

**Comment by Vultwo** [comment]
No problem, I am glad you fixed it
