### ISSUE TITLE
for loop without 'var' causes errors in some environments 

### ISSUE THREAD

**Issue by C451** [Bitvested/ta.js#16]
Hello, 

Running your cool lib in electron and caught an error: for some reason node requires 'var' in the for loop: 

https://github.com/Bitvested/ta.js/blob/main/index.js#L404

<img width="459" alt="image" src="https://user-images.githubusercontent.com/48596328/202523396-e7df8f06-2e25-42cc-bcc0-32d311182b17.png">

**Comment by Vultwo** [comment]
Hi, it should be fixed now.
Let me know if you encounter any other issues.
