### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by C451** [Bitvested/ta.js#17]
Hi again, you can easily add browser support by checking existence of `process`.  https://github.com/Bitvested/ta.js/blob/main/index.js#L1

I have to implement it like this for now:
```js
 window.process = { versions: { node: '0.0' } }
```

**Comment by Vultwo** [comment]
Hi, sorry for the late response.
That first line of code is actually to check if someone has access to the worker_threads module.
Or do you mean something else?

**Comment by C451** [comment]
Yes, but if you want to use the library in the browser, it throws something like "**process** not found". So you could check if it exists.

**Comment by Vultwo** [comment]
Thanks for the suggestion. Update is online.

**Comment by C451** [comment]
Although the right way is to check `typeof process === 'object'` 
<img width="428" alt="image" src="https://user-images.githubusercontent.com/48596328/205053043-c160e92b-6bbc-4730-a4db-7ef9009ed290.png">

**Comment by Vultwo** [comment]
Oops my bad, fixing it right away.

**Comment by Vultwo** [comment]
It should be working now.
