### ISSUE TITLE
rsi divergence

### ISSUE THREAD

**Issue by btm2021** [Bitvested/ta.js#18]
hi devs. first thanks your amazing lib. 
divergence is important of TA. could you implement to ta.js
example here 
https://www.tradingview.com/script/AkWCX6pt-RSI-Divergence-Indicator-w-Alerts/
this is rsi divergence.

thanks for amazing lib.

**Comment by Vultwo** [comment]
Hi, thank you.
Unfortunately I'm not very good at converting Pine Script code to JavaScript.
I will keep the issue open if anyone wants to decide to help.

**Comment by btm2021** [comment]
tks for reply.
here is sample about detect diverger 
is python :https://github.com/SpiralDevelopment/RSI-divergence-detector
in js : https://github.com/bkawk/divergence

in sample js 

To detect the divergence of the relative strength index (RSI) and price in JavaScript, you can use the following steps:

Calculate the RSI values for a given time period, using the following formula:
RSI = 100 - (100 / (1 + (average of up days / average of down days)))

Calculate the price change for the same time period, by subtracting the first closing price from the last closing price.

If the price has increased and the RSI has decreased, or if the price has decreased and the RSI has increased, then there is a divergence between the RSI and price.

Here's some example code that demonstrates these steps:

Copy code
function detectDivergence(prices, timePeriod) {
  // Calculate the RSI values
  let upDays = 0;
  let downDays = 0;
  for (let i = 1; i < timePeriod; i++) {
    let priceChange = prices[i] - prices[i - 1];
    if (priceChange > 0) {
      upDays += priceChange;
    } else {
      downDays -= priceChange;
    }
  }
  let avgUpDays = upDays / timePeriod;
  let avgDownDays = downDays / timePeriod;
  let rs = avgUpDays / avgDownDays;
  let rsi = 100 - (100 / (1 + rs));

  // Calculate the price change
  let priceChange = prices[timePeriod - 1] - prices[0];

  // Check for divergence
  if ((priceChange > 0 && rsi < 0) || (priceChange < 0 && rsi > 0)) {
    console.log("There is a divergence between the RSI and price");
  } else {
    console.log("There is no divergence between the RSI and price");
  }
}

let prices = [100, 105, 110, 100, 95, 105];
detectDivergence(prices, 3); // There is no divergence between the RSI and price


here is javascript convert of pinescript 
function rsiDivergenceIndicator(data, len, src, lbR, lbL, rangeUpper, rangeLower, plotBull, plotHiddenBull, plotBear, plotHiddenBear) {
  const osc = rsi(src, len);
  const obLevel = hline(70);
  const osLevel = hline(30);
  const plFound = pivotlow(osc, lbL, lbR);
  const phFound = pivothigh(osc, lbL, lbR);
  const _inRange = (cond) => {
    const bars = barssince(cond === true);
    return rangeLower <= bars && bars <= rangeUpper;
  }

  // Regular Bullish
  const oscHL = osc[lbR] > valuewhen(plFound, osc[lbR], 1) && _inRange(plFound[1]);
  const priceLL = low[lbR] < valuewhen(plFound, low[lbR], 1);
  const bullCond = plotBull && priceLL && oscHL && plFound;

  // Hidden Bullish
  const oscLL = osc[lbR] < valuewhen(plFound, osc[lbR], 1) && _inRange(plFound[1]);
  const priceHL = low[lbR] > valuewhen(plFound, low[lbR], 1);
  const hiddenBullCond = plotHiddenBull && priceHL && oscLL && plFound;

  // Regular Bearish
  const oscLH = osc[lbR] < valuewhen(phFound, osc[lbR], 1) && _inRange(phFound[1]);
  const priceHH = high[lbR] > valuewhen(phFound, high[lbR], 1);
  const bearCond = plotBear && priceHH && oscLH && phFound;

  // Hidden Bearish
  const oscHH = osc[lbR] > valuewhen(phFound, osc[lbR], 1) && _inRange(phFound[1]);
  const priceLH = high[lbR] < valuewhen(phFound, high[lbR], 1);
  const hiddenBearCond = plotHiddenBear && priceLH && oscHH && phFound;

 please consider add to your lib. tks so much.

**Comment by Vultwo** [comment]
Thanks for the code, I'll try to add this as soon as possible.
I hope to have a updated version of the library online by next week.

**Comment by btm2021** [comment]
if lib have divengencer it is big move. 
tks so much.

**Comment by Vultwo** [comment]
Hi, I have uploaded a new version.
Could you check if it actually does what you need it to do.
I couldn't figure out what these values meant:

// Regular Bullish
const oscHL = osc[lbR] > valuewhen(plFound, osc[lbR], 1) && _inRange(plFound[1]);
const priceLL = low[lbR] < valuewhen(plFound, low[lbR], 1);
const bullCond = plotBull && priceLL && oscHL && plFound;

// Hidden Bullish
const oscLL = osc[lbR] < valuewhen(plFound, osc[lbR], 1) && _inRange(plFound[1]);
const priceHL = low[lbR] > valuewhen(plFound, low[lbR], 1);
const hiddenBullCond = plotHiddenBull && priceHL && oscLL && plFound;

// Regular Bearish
const oscLH = osc[lbR] < valuewhen(phFound, osc[lbR], 1) && _inRange(phFound[1]);
const priceHH = high[lbR] > valuewhen(phFound, high[lbR], 1);
const bearCond = plotBear && priceHH && oscLH && phFound;

// Hidden Bearish
const oscHH = osc[lbR] > valuewhen(phFound, osc[lbR], 1) && _inRange(phFound[1]);
const priceLH = high[lbR] < valuewhen(phFound, high[lbR], 1);
const hiddenBearCond = plotHiddenBear && priceLH && oscHH && phFound;

**Comment by Vultwo** [comment]
RSI Divergence (from docs)
```javascript
var data = [74,83,66,78,69,70,84,73,74,73,83];
var rsi_length = 5;
var rsi_function = ta.wrsi; // default (the tradingview rsi indicator)
await ta.rsi_divergence(data, rsi_length, rsi_function);
// output (array)
// [0, 0, 1, 0, 1, 0] (better to quantify if needed)
```

Code:
```javascript
async function rsi_divergence(data, length, rs) {
  if(!rs) rs = module.exports.wrsi;
  var rd = await rs(data, length), out = [];
  data = await module.exports.mom(data.slice(length-1, data.length), 2);
  for(var i = 0; i < data.length; i++) {
    if((data[i] > 0 && rd[i] < 0) || (data[i] < 0 && rd[i] > 0)) {
      out.push(1);
    } else {
      out.push(0);
    }
  }
  return out;
}
```

**Comment by btm2021** [comment]
<img width="549" alt="Screen Shot 2023-01-15 at 7 28 16 PM" src="https://user-images.githubusercontent.com/109046697/212540695-bce695b9-ad8e-41bf-9088-65dd83faae91.png">
<img width="293" alt="Screen Shot 2023-01-15 at 7 28 39 PM" src="https://user-images.githubusercontent.com/109046697/212540696-5e71a0c2-46b4-4de8-a594-37e9beed7693.png">
work like a charm. tks so much. good job men.

**Comment by phattranky** [comment]
Hi @btm2021 ,

Could you share your code how do you map the  `0 1` in the result to the price position as the above screenshot. Thanks

**Comment by phattranky** [comment]
Let's say I have the result is 
```
[0,1,1,0,1,0,0,0,0,0,1,1,1,1,1,1,0,0,0,0,1,0,0,1,1,0,0,1,0,1,0,0,0,1,1,1,1,1,0,0,0,1,0,0,1,0,1,0,1,0,0,0,1,1,1,0,0,1,1,0,0,1,0,0,0,0,0,1,0,1,1,0,1,1,0,0,0,0,0,1,0,0,0,1,0]
```

How can I know which point is the start point and endpoint to draw the line ?

**Comment by Vultwo** [comment]
> Let's say I have the result is
> 
> ```
> [0,1,1,0,1,0,0,0,0,0,1,1,1,1,1,1,0,0,0,0,1,0,0,1,1,0,0,1,0,1,0,0,0,1,1,1,1,1,0,0,0,1,0,0,1,0,1,0,1,0,0,0,1,1,1,0,0,1,1,0,0,1,0,0,0,0,0,1,0,1,1,0,1,1,0,0,0,0,0,1,0,0,0,1,0]
> ```
> 
> How can I know which point is the start point and endpoint to draw the line ?

@phattranky I'm not really sure how he maps the values in the array, my best guess is he just loops over it using a for loop.
The index zero of the output is the first value (oldest data point).
So you should splice the first values from the original data before putting them into the array.

**Comment by phattranky** [comment]
Thanks @Vultwo 

As I know, There are 6 kinds of Divergence. I mean with your function How can we detect it?

![diverCapture](https://user-images.githubusercontent.com/6443154/215317027-6cb784c8-c2dd-4fa9-876d-65d4b4f67307.JPG)

As your example

```
var data = [74,83,66,78,69,70,84,73,74,73,83];
var rsi_length = 5;
var rsi_function = ta.wrsi; // default (the tradingview rsi indicator)
await ta.rsi_divergence(data, rsi_length, rsi_function);
// output (array)
// [0, 0, 1, 0, 1, 0] (better to quantify if needed)
```

How can We know the divergence is bear or bull and which Candles (closed price) are connected become a line ?

@btm2021 in case you can help.

Thanks a lot

**Comment by phattranky** [comment]
Here is the code of TradingView, But I don't how to convert it to Javascript

```
// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © JayTradingCharts

//@version=4
//@version=4  
//---- thank to mohanee for the base code. we modified this to not give entries but instead alert on the just the divs 
study(title="RSI Divergence Indicator w/Alerts", format=format.price, resolution="")
len = input(title="RSI Period", minval=1, defval=14)
src = input(title="RSI Source", defval=close)
lbR = input(title="Pivot Lookback Right", defval=5)
lbL = input(title="Pivot Lookback Left", defval=5)
rangeUpper = input(title="Max of Lookback Range", defval=60)
rangeLower = input(title="Min of Lookback Range", defval=5)
plotBull = input(title="Plot Bullish", defval=true)
plotHiddenBull = input(title="Plot Hidden Bullish", defval=false)
plotBear = input(title="Plot Bearish", defval=true)
plotHiddenBear = input(title="Plot Hidden Bearish", defval=false)
bearColor = color.red
bullColor = color.green
hiddenBullColor = color.new(color.green, 80)
hiddenBearColor = color.new(color.red, 80)
textColor = color.white
noneColor = color.new(color.white, 100)
osc = rsi(src, len)

plot(osc, title="RSI", linewidth=2, color=#8D1699)
hline(50, title="Middle Line", linestyle=hline.style_dotted)
obLevel = hline(70, title="Overbought", linestyle=hline.style_dotted)
osLevel = hline(30, title="Oversold", linestyle=hline.style_dotted)
fill(obLevel, osLevel, title="Background", color=#9915FF, transp=90)

plFound = na(pivotlow(osc, lbL, lbR)) ? false : true
phFound = na(pivothigh(osc, lbL, lbR)) ? false : true
_inRange(cond) =>
	bars = barssince(cond == true)
	rangeLower <= bars and bars <= rangeUpper

//------------------------------------------------------------------------------
// Regular Bullish
// Osc: Higher Low

oscHL = osc[lbR] > valuewhen(plFound, osc[lbR], 1) and _inRange(plFound[1])

// Price: Lower Low

priceLL = low[lbR] < valuewhen(plFound, low[lbR], 1)
bullCond = plotBull and priceLL and oscHL and plFound

plot(
     plFound ? osc[lbR] : na,
     offset=-lbR,
     title="Regular Bullish",
     linewidth=2,
     color=(bullCond ? bullColor : noneColor),
     transp=0
     )

plotshape(
	 bullCond ? osc[lbR] : na,
	 offset=-lbR,
	 title="Regular Bullish Label",
	 text=" Bull ",
	 style=shape.labelup,
	 location=location.absolute,
	 color=bullColor,
	 textcolor=textColor,
	 transp=0
	 )

//------------------------------------------------------------------------------
// Hidden Bullish
// Osc: Lower Low

oscLL = osc[lbR] < valuewhen(plFound, osc[lbR], 1) and _inRange(plFound[1])

// Price: Higher Low

priceHL = low[lbR] > valuewhen(plFound, low[lbR], 1)
hiddenBullCond = plotHiddenBull and priceHL and oscLL and plFound

plot(
	 plFound ? osc[lbR] : na,
	 offset=-lbR,
	 title="Hidden Bullish",
	 linewidth=2,
	 color=(hiddenBullCond ? hiddenBullColor : noneColor),
	 transp=0
	 )

plotshape(
	 hiddenBullCond ? osc[lbR] : na,
	 offset=-lbR,
	 title="Hidden Bullish Label",
	 text=" H Bull ",
	 style=shape.labelup,
	 location=location.absolute,
	 color=bullColor,
	 textcolor=textColor,
	 transp=0
	 )

//------------------------------------------------------------------------------
// Regular Bearish
// Osc: Lower High

oscLH = osc[lbR] < valuewhen(phFound, osc[lbR], 1) and _inRange(phFound[1])

// Price: Higher High

priceHH = high[lbR] > valuewhen(phFound, high[lbR], 1)

bearCond = plotBear and priceHH and oscLH and phFound

plot(
	 phFound ? osc[lbR] : na,
	 offset=-lbR,
	 title="Regular Bearish",
	 linewidth=2,
	 color=(bearCond ? bearColor : noneColor),
	 transp=0
	 )

plotshape(
	 bearCond ? osc[lbR] : na,
	 offset=-lbR,
	 title="Regular Bearish Label",
	 text=" Bear ",
	 style=shape.labeldown,
	 location=location.absolute,
	 color=bearColor,
	 textcolor=textColor,
	 transp=0
	 )

//------------------------------------------------------------------------------
// Hidden Bearish
// Osc: Higher High

oscHH = osc[lbR] > valuewhen(phFound, osc[lbR], 1) and _inRange(phFound[1])

// Price: Lower High

priceLH = high[lbR] < valuewhen(phFound, high[lbR], 1)

hiddenBearCond = plotHiddenBear and priceLH and oscHH and phFound

plot(
	 phFound ? osc[lbR] : na,
	 offset=-lbR,
	 title="Hidden Bearish",
	 linewidth=2,
	 color=(hiddenBearCond ? hiddenBearColor : noneColor),
	 transp=0
	 )

plotshape(
	 hiddenBearCond ? osc[lbR] : na,
	 offset=-lbR,
	 title="Hidden Bearish Label",
	 text=" H Bear ",
	 style=shape.labeldown,
	 location=location.absolute,
	 color=bearColor,
	 textcolor=textColor,
	 transp=0
	 )
	 
	 

alertcondition(bullCond, title="Bull", message="Regular Bull Div {{ticker}} XXmin")
alertcondition(bearCond, title="Bear", message="Regular Bear Div {{ticker}} XXmin")
alertcondition(hiddenBullCond, title="H Bull", message="Hidden Bull Div {{ticker}} XXmin")
alertcondition(hiddenBearCond, title="H Bear", message="Hidden Bear Div {{ticker}} XXmin")

```

**Comment by Vultwo** [comment]
@phattranky The code seems to make use of pivot points to determine wether the current state is in regular or hidden.
This library also contains a function for calculating these pivot points (fractals or zigzag).
You could calculate the current state by determining wether the pivot points of the rsi and price are also diverging.
I will create a function for this, but I don't know when it's ready.

> As I know, There are 6 kinds of Divergence. I mean with your function How can we detect it?
> 
> ![diverCapture](https://user-images.githubusercontent.com/6443154/215317027-6cb784c8-c2dd-4fa9-876d-65d4b4f67307.JPG)

**Comment by phattranky** [comment]
@Vultwo Thanks  bro. Hope We can have it soon. It must a great function.

**Comment by baothihassio** [comment]
hi, i'am in holiday. @phattranky i just convert from timestamp rsi to ohcl. nothing eles. in vultwo function rsi point start 0 with mean it start div. and important is use div is choice right time for check div. 
@phattranky my picture is tradingview library. you can use here https://charting-library.tradingview-widget.com/
use this nodejs for scan and use tradingview lib get result of scan and marking to chart.what else i can help ?

**Comment by btm2021** [comment]
hello all, sorry because i in my holiday.
@phattranky i just get result and compare with timestamp of ohvcl.
in my picture is tradingview library. you can get here https://www.tradingview.com/HTML5-stock-forex-bitcoin-charting-library/?feature=technical-analysis-charts. 
get result of scan and format to right timestamp and use tradingview lib mark this scan.
it not thing else.

**Comment by btm2021** [comment]
important when check div is use right point. example. u can use pivot of ta.js and detect important zone of price and important zone of rsi and use function div to check.
hidden div i think not useful because it not right, hidden div just simple lag of price or bigboy make market move. if you use hidden div it very noise. just check div regular. and make your choice.

**Comment by btm2021** [comment]
and important. div is technical like rsi or bb. you should combine more signal to confirm your signal.

**Comment by btm2021** [comment]
here my function got result and compare with ohcvl
function arrangeResult(result, length) {
    for (i = 0; i < length - 1; i++) {
        result.unshift(0)
    }
    return result;
}
example ema.  
let result = await ta.ema(data, period);
        result = arrangeResult(result, period);
because nodejs not pandas like python. use this func and put together.

**Comment by btm2021** [comment]
@Vultwo, i have write some function check swing high and swing low. and some func. utils. can you add to your lib ?

**Comment by phattranky** [comment]
Thanks @btm2021 ,

Instead of drawing on the chart, can we detect it on the code side?  My idea is to create a bot that scans all the candle values in a period of time and notify to the user when they detect any divergence.

The result expected may be like 

```
BTC has the regular bear closed on 15:00 - 1H
```

**Comment by btm2021** [comment]
@phattranky hi, sorry i just write frond-end ui, grap data and show to chart, your idead seem interesting but i don't know how to write for that. sorry man

**Comment by phattranky** [comment]
Thanks @btm2021 . Yes scanning all the coins at the background is more effective than We have to check the UI one by one =))

**Comment by Vultwo** [comment]
> @Vultwo, i have write some function check swing high and swing low. and some func. utils. can you add to your lib ?

Is this different from the zigzag and fractal indicators that are already in the library? All functions are welcome if you're willing to share them.

**Comment by btm2021** [comment]
oh, i checked, it calc base high low and high swing and your zigzag do the same. my bad.

**Comment by Vultwo** [comment]
Sorry for the long wait @phattranky I'm still developing the function. The function won't be perfect though. The divergence can be in multiple states at once. The historical signal values of the function also wouldn't be perfect as the states can changes as more data is coming in. I'm finishing the function over the weekend.

**Comment by phattranky** [comment]
Great. Thanks a  lot, @Vultwo .  I will check and get back to you later

**Comment by phattranky** [comment]
Hi @Vultwo 

I have some questions, Could you help me to clarify?

1. The data1 and data2 are the closed price values and RSI values, right?
2. The `convergence` is meaning the normal state, right?
3. If the question 2 is correct. Could you identify the bearish and bullish divergence like the `exaggerated_bearish` and `exaggerated_bullish`?

Thanks.

**Comment by Vultwo** [comment]
Hi @phattranky,

1. Yes.
2. Convergence is the state when no divergence takes place.
3. The outputted states are: "exaggerated_bearish", "exaggerated_bullish", "hidden_bearish", "hidden_bullish", "regular_bearish", "regular_bullish". When none of these states is found (according to the threshold values for exaggerated / regular) the value outputted will be "divergence".

The problem with the trading view indicator is that the states only become known after the data has past. It is hard to predict the state as the data is coming in as it easily changes the state.

**Comment by phattranky** [comment]
Thanks @Vultwo 

I will check again. Because I'm confusing the state of your example. I see it is 

```
// output (array of arrays)
// [['convergence'],['divergence'],['convergence'],['divergence'],['convergence'],['exaggerated_bearish']]
```

So I thought those are the state values.

**Comment by phattranky** [comment]
Hi @Vultwo 

I wrote an example code here https://github.com/phattranky/ta-rsi-divergence-example/blob/main/index.js

Could you help me to check why it doesn't have any divergence? Any wrong with my configuration?
I found some divergence in that range on the Chart.

You can try to change the `pair` and `startTime` `endTime` on my code for back testing.


![5555LINKUSDTPERP 7 401 ▲ +6 57% Vô danh 2023-03-30 04-52-34](https://user-images.githubusercontent.com/6443154/228676261-ec530177-f58a-432a-8983-e2922bd6d2b2.png)
![44444index js — ta-rsi-divergence-example 2023-03-30 04-50-08](https://user-images.githubusercontent.com/6443154/228676281-50370362-77cd-4290-a89f-4fbc1100f8fb.png)

**Comment by phattranky** [comment]
Thanks @Vultwo .

You're so nice. Seems it's working. Let's me test more and get back to you later
