### ISSUE TITLE
WIlder's RSI

### ISSUE THREAD

**Issue by usaccounts** [Bitvested/ta.js#2]
Add wilder's smooth RSI.

**Comment by Vultwo** [comment]
Added

**Comment by usaccounts** [comment]
thank you :) alternative

function gain(data) {
    let ret = []
    for (let i = 1; i < data.length; i++) {
        ret.push(Math.max(0, data[i] - data[i - 1]))
    }
    return ret
}
function loss(data) {
    let ret = []
    for (let i = 1; i < data.length; i++) {
        ret.push(-Math.min(0, data[i] - data[i - 1]))
    }
    return ret
}

function rma(data, len) {
    return ema(data, len, 1 / len)
}

export function wrsi(data, len) {
    var length = (!len) ? 14 : len
    let rsi = []
    let gains = gain(data)
    let losses = loss(data)
    let up =   (rma(gains, len))
    let down = (rma(losses, len))
    for (let i = len; i < data.length; i++) {
        rsi.push(100 - (100 / (1 + up[i-len] / down[i-len])))
    }
    return rsi
}
