### ISSUE TITLE
Bug: Can't resolve 'worker_threads'

### ISSUE THREAD

**Issue by haydar-can** [Bitvested/ta.js#23]
I wanted to use ta.js to use it in an electronjs application. However;

**ERROR in ./node_modules/ta.js/multi/multi.js 4:4-29
Module not found: Error: Can't resolve 'worker_threads' in** 

error appears on the screen.

**import { ren as Renko } from 'ta.js';**

I'm calling as.

Thank you.

**Comment by Vultwo** [comment]
Hi,

You should use this version of the package: https://github.com/Bitvested/ta.web
