### ISSUE TITLE
Missing Dependency in Project

### ISSUE THREAD

**Issue by Smackface** [Bitvested/ta.js#8]
![image](https://user-images.githubusercontent.com/81190891/156637111-f88cb8b4-74d4-4dea-9c2c-5c515e748f91.png)

I installed it and tried to run, and got this.

**Comment by Vultwo** [comment]
What node version are you using?

**Comment by Smackface** [comment]
14.16.0

**Comment by Vultwo** [comment]
I can't seem to reproduce this issue. It's weird because worker_threads is a standard node module.
I have created a possible fix. Could you let me know if the update is working?

**Comment by Smackface** [comment]
![image](https://user-images.githubusercontent.com/81190891/156653685-1b3038ed-0e1e-4fbe-9002-7747b6a9c583.png)
![image](https://user-images.githubusercontent.com/81190891/156653700-fd304fc3-ffa2-4886-b54e-9ea99a99bfe6.png)
This is what I get now

**Comment by Vultwo** [comment]
I'm not sure what frameworks you are using, so I can't say what is going wrong exactly.
Your easiest fix would be to create a file and copy the contents of:
https://github.com/Bitvested/ta.js/blob/main/index.js

Make sure to remove all references of "multi" before you import or require the file to access the functions.

**Comment by Vultwo** [comment]
I'm not familiar with the web frameworks but I have also got a minified version on UNPKG.
Maybe you could try to import that to keep the version up to date:

https://unpkg.com/ta.js/ta.min.js

**Comment by Vultwo** [comment]
I have created a react compatible version of this package here:
https://github.com/Bitvested/ta.web
